.github/workflows/buildcheck.yml
Signed-off-by: Gunnar Andersson <gandersson@genivi.org>
=> Use 3.8 for unit tests instead

model/vsc_parser.py, templates/simple_overview.tpl
Tooling previously searched for "in_arguments" rather than "in".
Also fixed a printout in example template
=> Fixing tooling error for events

Pipfile, Pipfile.lock, README.md, requirements.txt
As stated inside #12, this repository is lacking dependency files to easily install through _pipenv_ or _pip_ tools the dependencies needed by vsc_tools
* adds Pipfile and Pipfile.lock to allow to easily install through pipenv the needed dependencies used by vsc tools
* adds requirements.txt to allow the same above usage but with pip install
* README.md is updated in accordance
- This work is mainly inspired by what has been done inside vss-tools
- I haven't do the job about setuptools files. Let me know if this part is needed or not ? Knowing that currently, seems there are still a lot of work in progress inside this repository (let me know if I'm wrong)
=> adds package dependencies based on pipenv and pip tools

model/vsc_parser.py, templates/Service-simple_doc.html, templates/sds-bamm-macros.tpl, templates/simple_overview.tpl, tests/input
First change to update parser to match current description of the VSC
syntax (as stated in README.md of vehicle_service_catalog, _currently_)
(There could still be some bugs in either this code, and/or the description in the README, but this brings the tools at least roughly up to date with what is described there).
=> Update parser to match language as defined in README.md

.github/workflows/buildcheck.yml, Pipfile, Pipfile.lock, README.md, model/vsc_generator.py, model/vsc_parser.py, templates/AST-simple_doc.tpl, templates/Service-simple_doc.html
This is a completely rewritten parser (and some resulting modifications to generator) that is more "schema-driven".   The VSC language is defined with a data structure that is like a "schema" or language definition, and a generic engine is operating on that.
=> Data driven parser

README.md
Additional updates.   We have a lot of different ways to install now.  I had been using `pyenv` but recently Mikhail added `python -m venv venv`, which is yet another thing, not identical to `pyenv` as I understand it.
So, maybe there are too many ways now but I think this README at least documents them.
I also deprecated `pipenv` method until we get a setup that seems to work correctly.
=> README: Update all setup/installation instructions

.github/workflows/buildcheck.yml, Pipfile.lock, vsc/templates/dtdl.md, vsc/templates/dtdl.tpl, vsc/templates/protobuf.md, vsc/templates/protobuf.tpl, vsc/templates/sds-bamm-aspect-model.md, vsc/templates/sds-bamm-aspect-model.tpl, vsc/templates/sds-bamm-macros.tpl
Fixes the following problems:
- Top item is now a "service" (i.e. one level in tree removed)
- In/Out renamed to Input/Output
- Line-break handling for descriptions. The seat example service uses it quite a lot, the target languages here does not support it, at least not without escapes. For now just removing line breaks.
Also extending CI checks for templates. This practically means that any changes introduced to tools or to the example seat service causing regressions will be detected. 
Signed-off-by: Erik Jaegervall <erik.jaegervall@se.bosch.com>
=> Fix template regressions

ifex/model/ifex_ast.py
This was a mistake in previous definitions.  There is no need to have a type field for structs since they are already grouped under the structs: parent node.
=> ifex_ast: Remove type from Struct

.github/workflows/buildcheck.yml, requirements.txt
Run D-Bus generator (on one file from VSC, like the others) as part of buildcheck
(Note that this workflow WILL FAIL until https://github.com/COVESA/vehicle_service_catalog/pull/49 is merged)  
EDIT: It is now merged.
=> workflows: Add D-Bus to basic checks

ifex/model/ifex_ast_doc.py, ifex/model/ifex_ast_introspect.py
Pushing an old refactor job.
This separates the functions that "introspect" the language definition in ifex_ast.py, away from the document generation task in ifex_ast_doc.py.  
Because these functions that "introspect" the model that defines the core IDL, are reusable for other things than document definition.  The implementation of this is now more complete, robust, and cleaner too.
=> Refactor doc generation

docs/README.md
The links in README.md inside of docs/ work correctly when viewed through GitHub pages, but if someone looked directly at the README in the code repository, the links go to not-yet-generated documentation files, and this was not obvious.  Now, by linking directly to the published GitHub pages explicitly, the links will work also when viewed inside of the code repository.
----
=> docs: Make README links work if viewed in code repository

.github/workflows/buildcheck.yml, ifex/model/ifex_ast.py, ifex/model/ifex_ast_introspect.py, ifex/schema/LICENSE.README.md, ifex/schema/LICENSE.json-schema, ifex/schema/README.md, ifex/schema/ifex_to_json_schema.py, ifex/schema/json-schema.org_draft_2020-12_schema, ifex/schema/pretty_print_json.py, ifex/schema/validate.py, requirements.txt
- Please refer to #97 for detailed explanation
Also, a similar explanation, and more of the history is provided in **README.md** in this PR.
=> Add JSON-schema generator

ifex/model/ifex_ast.py
At an early stage, the top level was defined by a toplevel namespace.
However the specification/examples treats the top level slightly differently.
In the meantime, some of the code was tested by treating Namespace to top level node instead of the AST type and (in quite a sloppy way) just achieving that by inheriting Namespace.
This commit is an old fix that should have been pushed a long time ago. It brings things into order by clearly defining the file top-level (represented by the AST class) as an independent thing.
From here, we are back in sync with the _current_ formal specification, and we can from there proceed to make slight modifications - such as clarifying where the versioning should occur (it should be applied to an Interface, not on "file" level) and other quality …
=> Define AST without inheriting Namespace

ifex/model/ifex_ast_construction.py, ifex/model/type_checking_constructor_mixin.py
To create an AST, it is possible to call functions that return the dataclass objects. That is of course nothing more than a normal constructors (`__init__()` functions), but this implementation also does some checking of the inputs so they adhere to the specified model.
Further explanation is best read from the comments inside of [ifex_ast_construction.py](https://github.com/gunnar-mb/ifex/blob/ifex_construction/ifex/model/ifex_ast_construction.py)
----
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INF …
=> ifex_construction = support for building IFEX AST trees

ifex/model/ifex_ast.py, ifex/model/ifex_ast_introspect.py, ifex/model/type_checking_constructor_mixin.py, other/protobuf/README.md, other/protobuf/protobuf.grammar, other/protobuf/protobuf_ast.py, other/protobuf/protobuf_ast_construction.py, other/protobuf/protobuf_lark.py, other/protobuf/protobuf_to_ifex.py, other/protobuf/test_convert_uservices.sh
This adds code to read protobuf / gRPC definitions and convert them to IFEX model.
There are some known limitations and some features that might not make sense in a non-gRPC environment (further discussion needed).   This stage is to show the feasibility and the base infrastructure that is needed for conversions.
Features that are not supported (not accepted by parser):
- extend
Features that are now _parsed_ but not converted to anything specific on the IFEX side (discussion needed)
- reserved, oneOf, mapField, import, stream, all options
Some other corner-cases and forgotten things might also still be here.
----
The …
=> protobuf/gRPC support (as input language)

ifex/model/ifex_ast_construction.py, ifex/schema/ifex_to_json_schema.py, tests/gen_test.py
Author: Manuel Böhm <[manuel.boehm@mercedes-benz.com](mailto:manuel.boehm@mercedes-benz.com)>, on behalf of MBition GmbH.
Currently the fundamental types used in [ifex_ast.py](https://github.com/COVESA/ifex/blob/master/ifex/model/ifex_ast.py) are only [str, int] and the code reflects that. To make the code more future-proof and complete further types are added.
Some other corner-cases and forgotten things might also still be here.
---
=> Fixes #109: Fundamental types used in ifex_ast.py

.github/workflows/buildcheck.yml, docker/Dockerfile.alpine, docker/Dockerfile.ubuntu, requirements.txt, setup.py
These are related changes because python 3.12 removed distutils which requires a change to setup.py
but setup.py should ideally still work with older versions.
New CI setup uses a matrix approach testing with a few older versions.
One dependency (lark) was missed in the addition of protobuf support previously.
----
=> CI: testing more python versions, and fixing dependencies

.github/workflows/buildcheck.yml, ifex/scripts/protobuf_ifex.py, other/protobuf/protobuf_ast_construction.py, other/protobuf/protobuf_lark.py, other/protobuf/protobuf_to_ifex.py, setup.py
Before this, the functionality could only be tested from within the implementation directory.
After this, there is a user entry-point command script ifexconv_protobuf, which is similar to implemented entry-points for other functions before.  Changes are also made to properly install the modules when setup.py is executed.
----
=> Protobuf/grpc: Add proper module/script installation and CI build test

.github/workflows/generate_docs.yml, docs/create-toc.py, docs/def-specification.stage1.m.md, docs/generate-types-doc.py, ifex/model/ifex_ast.py
Generate documentation from the fundamental types definitions
Note: These are older commits that were not written during MBition employment, so no further comments necessary.
=> Generate types docs

ifex/generators/DBus/dbus_types.py, ifex/model/types.yml, ifex/templates/sds-bamm/sds-bamm-macros.tpl
It wasn't really implemented in several places anyway, but this removes some remaining references to this type.
The byteBuffer type is superfluous since it can be represented by an array of uint8.  It was at an earlier time also removed from the VSS project.  Another alternative is the IFEX 'opaque' type. It was conceived to indicate that something in reality has structure but that it cannot (or is chosen not to) have a detailed represented in the IFEX description.  An Opaque type is presumably also transferred as "just a bunch of bytes" in a computing system - only the name infers there is some additional meaning.
Note: These are older commits that were not written during MBition employment.
=> Remove byteBuffer type (use array of bytes)

ifex/model/stable_sort_ifex.py, ifex/scripts/diff_ifex.py
stable_sort_ifex defines a known order of keys so that IFEX files can be reliably compared.  
It is a module but can also be run as a standalone script.
The diff_ifex.py script will print the diff between two files, after normalizing the order of the content using the stable_sort_ifex module.  
In combination, these are useful tools for future regression testing.
Note: These are older commits that were not written during MBition employment
=> Programs to "sort" and compare IFEX content

.github/workflows/create-new-release.yml, ifex/schema/ifex_to_json_schema.py
=> Automated tagging/release workflow, including the JSON schema file

ifex/model/ifex_ast.py
The two identifiers are initially not really necessary for IFEX Core IDL files, but they are added to prepare for easier differentiating between multiple type of files.  
**The intention is that all Layer Types shall also include the same fields.**
`filetype:` is used to indicate the layer type by name
`schema:` indicates through filename or URI the JSON schema file that defines the format of the Layer Type, which can thus be used to check conformance of the layer.
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/P …
=> AST: Add filetype and schema fields

.github/workflows/buildcheck.yml, .github/workflows/create-new-release.yml, .github/workflows/generate_docs.yml, docker/Dockerfile.alpine, docker/Dockerfile.ubuntu, ifex/model/ifex_ast.py
This was an obvious typo, noticed only now.  Maybe some kind of redefinition would put this in a single place instead (DRY) but there are a few differences between concepts that might make that inconvenient.  Worth considering later - this is more of a quick fix.
=> Bugfix: arraysize on Error shall be int, had wrong type

ifex/model/ifex_ast.py, ifex/model/ifex_ast_construction.py, ifex/model/type_checking_constructor_mixin.py, other/franca/franca_to_ifex.py, other/franca/print_franca_tree.py, other/franca/rule_translator.py, requirements.txt
There are a few known unsupported Franca features and probably a few bugs.
- "Manages" not yet implemented, and possibly a few others
- Some variations of import statements fail (possibly problem in pyfranca)
- Probably some other corner cases.  
This can be merged so that further work can be done and contributed.  It will also enable a round of improvements on test suites and CI and such.
=> Franca translation and introducing table/rule-based framework for translation

Pipfile, models/ifex/ifex_ast.py, models/ifex/ifex_parser.py, models/ifex/merge_models.py, tests/gen_test.py, tests/merge_tree/async, tests/merge_tree/five, tests/merge_tree/four, tests/merge_tree/four+five, tests/merge_tree/one, tests/merge_tree/one+three, tests/merge_tree/one+two, tests/merge_tree/three, tests/merge_tree/two, tests/test_merge_tree.py, transformers/merge_overlay.py
This implements the rules for merging trees.  So far the implementation only allows for "overlays" - i.e. modifying layers that are using the Core IFEX IDL definition -- some changes to allow for parsing new layer types is needed, as new layer types will not be accepted by the strict parser for the IFEX Core.
The unit tests have been extended to demonstrate and check the functionality.
=> Merge overlays
